# Generated by Django 4.2 on 2026-01-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_ticket_fecha_asignacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='area_trabajo',
            field=models.CharField(choices=[('IT', 'Soporte Técnico'), ('HR', 'Recursos Humanos'), ('FN', 'Finanzas'), ('MK', 'Marketing'), ('VN', 'Ventas'), ('LG', 'Legal'), ('PR', 'Proyectos'), ('AD', 'Administración'), ('OP', 'Operaciones'), ('AL', 'Almacén / Logística'), ('QA', 'Calidad')], default='OT', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('AB', 'Abierto'), ('EP', 'En Proceso'), ('RS', 'Resuelto'), ('CR', 'Cerrado'), ('DS', 'Descartado')], default='AB', max_length=2),
        ),
    ]
