# Generated by Django 4.2 on 2025-10-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_titulo_ticket_creador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='fecha_asignacion',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='fecha_resolucion',
        ),
        migrations.AddField(
            model_name='ticket',
            name='area_trabajo',
            field=models.CharField(choices=[('IT', 'Soporte Técnico'), ('HR', 'Recursos Humanos'), ('FN', 'Finanzas'), ('OT', 'Otro')], default='OT', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='asunto',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
